import { useState, useEffect, useRef, useId } from 'react'
import { X } from '../../lib/icons'
import { upsertMember } from '../../lib/members'

const TIERS = ['member', 'staff']

/**
 * Modal for adding or editing a member.
 * Props:
 *   member   — null for new member, object for editing
 *   onClose  — called to close the modal
 *   onSaved  — called after successful save
 */
export default function MemberFormModal({ member, onClose, onSaved }) {
  const isEditing = member != null
  const titleId = useId()
  const firstInputRef = useRef(null)
  const overlayRef = useRef(null)

  const favouriteDrinksInitial = Array.isArray(member?.favourite_drinks)
    ? member.favourite_drinks.join(', ')
    : member?.favourite_drinks ?? ''

  const [form, setForm] = useState({
    name: member?.name ?? '',
    membership_number: member?.membership_number ?? '',
    phone: member?.phone ?? '',
    email: member?.email ?? '',
    membership_tier: member?.membership_tier ?? 'member',
    renewal_date: member?.renewal_date ?? '',
    notes: member?.notes ?? '',
    favourite_drinks: favouriteDrinksInitial,
  })
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    firstInputRef.current?.focus()
  }, [])

  useEffect(() => {
    function handleKey(e) {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handleKey)
    return () => document.removeEventListener('keydown', handleKey)
  }, [onClose])

  function handleOverlayClick(e) {
    if (e.target === overlayRef.current) onClose()
  }

  function handleChange(field) {
    return e => setForm(prev => ({ ...prev, [field]: e.target.value }))
  }

  async function handleSubmit(e) {
    e.preventDefault()
    setSaving(true)
    setError(null)
    try {
      const drinksArray = form.favourite_drinks
        .split(',')
        .map(d => d.trim())
        .filter(Boolean)

      const payload = {
        ...(isEditing ? { id: member.id } : {}),
        name: form.name.trim(),
        membership_number: form.membership_number.trim(),
        phone: form.phone.trim() || null,
        email: form.email.trim() || null,
        membership_tier: form.membership_tier,
        renewal_date: form.renewal_date || null,
        notes: form.notes.trim() || null,
        favourite_drinks: drinksArray.length > 0 ? drinksArray : null,
        active: true,
      }

      // Remove empty membership_number for new members (auto-generated by upsertMember)
      if (!isEditing && !payload.membership_number) {
        delete payload.membership_number
      }

      await upsertMember(payload)
      onSaved()
    } catch (err) {
      setError(err.message ?? 'An error occurred. Please try again.')
      setSaving(false)
    }
  }

  return (
    <div
      ref={overlayRef}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 overflow-y-auto"
      onClick={handleOverlayClick}
      aria-hidden="false"
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        className="w-full max-w-lg bg-[#0F172A] border border-slate-700 rounded-2xl shadow-xl flex flex-col my-auto"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 pt-5 pb-4 border-b border-slate-700">
          <h2
            id={titleId}
            className="text-lg font-bold text-white"
          >
            {isEditing ? 'Edit Member' : 'Add Member'}
          </h2>
          <button
            onClick={onClose}
            aria-label="Close modal"
            className="text-slate-400 hover:text-white transition-colors cursor-pointer min-h-[44px] min-w-[44px] flex items-center justify-center rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
          >
            <X size={20} aria-hidden="true" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="px-5 py-5 flex flex-col gap-4">
          {error && (
            <p role="alert" className="text-red-400 text-sm bg-red-400/10 px-3 py-2 rounded-lg">
              {error}
            </p>
          )}

          {/* Name */}
          <div className="flex flex-col gap-1">
            <label htmlFor="mf-name" className="text-sm font-medium text-slate-300">
              Name <span aria-hidden="true">*</span>
            </label>
            <input
              ref={firstInputRef}
              id="mf-name"
              type="text"
              required
              value={form.name}
              onChange={handleChange('name')}
              placeholder="Full name"
              className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
            />
          </div>

          {/* Membership number */}
          <div className="flex flex-col gap-1">
            <label htmlFor="mf-membership-number" className="text-sm font-medium text-slate-300">
              Membership Number{!isEditing && <span className="text-slate-500 font-normal"> (auto-generated if blank)</span>}
              {isEditing && <span aria-hidden="true"> *</span>}
            </label>
            <input
              id="mf-membership-number"
              type="text"
              required={isEditing}
              value={form.membership_number}
              onChange={handleChange('membership_number')}
              placeholder="e.g. M0001"
              className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
            />
          </div>

          {/* Phone + Email */}
          <div className="grid grid-cols-2 gap-3">
            <div className="flex flex-col gap-1">
              <label htmlFor="mf-phone" className="text-sm font-medium text-slate-300">
                Phone <span className="text-slate-500 font-normal">(optional)</span>
              </label>
              <input
                id="mf-phone"
                type="tel"
                value={form.phone}
                onChange={handleChange('phone')}
                placeholder="07700 000000"
                className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
              />
            </div>
            <div className="flex flex-col gap-1">
              <label htmlFor="mf-email" className="text-sm font-medium text-slate-300">
                Email <span className="text-slate-500 font-normal">(optional)</span>
              </label>
              <input
                id="mf-email"
                type="email"
                value={form.email}
                onChange={handleChange('email')}
                placeholder="name@example.com"
                className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
              />
            </div>
          </div>

          {/* Tier + Renewal date */}
          <div className="grid grid-cols-2 gap-3">
            <div className="flex flex-col gap-1">
              <label htmlFor="mf-tier" className="text-sm font-medium text-slate-300">
                Membership Tier <span aria-hidden="true">*</span>
              </label>
              <select
                id="mf-tier"
                required
                value={form.membership_tier}
                onChange={handleChange('membership_tier')}
                className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white min-h-[44px] capitalize focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617] cursor-pointer"
              >
                {TIERS.map(t => (
                  <option key={t} value={t} className="capitalize">{t}</option>
                ))}
              </select>
            </div>
            <div className="flex flex-col gap-1">
              <label htmlFor="mf-renewal-date" className="text-sm font-medium text-slate-300">
                Renewal Date <span className="text-slate-500 font-normal">(optional)</span>
              </label>
              <input
                id="mf-renewal-date"
                type="date"
                value={form.renewal_date}
                onChange={handleChange('renewal_date')}
                className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617] cursor-pointer"
              />
            </div>
          </div>

          {/* Favourite drinks */}
          <div className="flex flex-col gap-1">
            <label htmlFor="mf-favourite-drinks" className="text-sm font-medium text-slate-300">
              Favourite Drinks <span className="text-slate-500 font-normal">(comma-separated, optional)</span>
            </label>
            <input
              id="mf-favourite-drinks"
              type="text"
              value={form.favourite_drinks}
              onChange={handleChange('favourite_drinks')}
              placeholder="Guinness, Jameson, Coke"
              className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 min-h-[44px] focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
            />
          </div>

          {/* Notes */}
          <div className="flex flex-col gap-1">
            <label htmlFor="mf-notes" className="text-sm font-medium text-slate-300">
              Notes <span className="text-slate-500 font-normal">(optional)</span>
            </label>
            <textarea
              id="mf-notes"
              rows={3}
              value={form.notes}
              onChange={handleChange('notes')}
              placeholder="Any additional notes…"
              className="bg-[#1E293B] border border-slate-600 rounded-lg px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617] resize-none"
            />
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-1">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 min-h-[44px] rounded-xl border border-slate-600 text-slate-300 hover:bg-slate-700 hover:text-white transition-colors cursor-pointer text-sm font-medium focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="flex-1 min-h-[44px] rounded-xl bg-[#22C55E] hover:bg-green-400 disabled:opacity-50 disabled:cursor-not-allowed text-slate-900 font-bold text-sm transition-colors cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-[#020617]"
            >
              {saving ? 'Saving…' : isEditing ? 'Save Changes' : 'Add Member'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
